#!/usr/bin/env bash
# build-atmosphere-smarttube.sh — build the ATMOSphere-SmartTube APK and
# copy it into the ATMOSphere prebuilt-apps tree for inclusion in the
# system image.
#
# Usage (from ATMOSphere parent repo root OR from this directory):
#     bash device/rockchip/atmosphere/smarttube-player/build-atmosphere-smarttube.sh
# or simply
#     cd device/rockchip/atmosphere/smarttube-player && bash build-atmosphere-smarttube.sh
#
# What it does:
#   1. Locates the ATMOSphere parent repo root (contains scripts/build.sh).
#   2. Runs ./gradlew :smarttubetv:assembleStstableRelease in this
#      submodule to produce the release APK (stable flavor →
#      applicationId org.smarttube.stable).
#   3. Copies the APK to
#      <atmosphere>/device/rockchip/rk3588/prebuilt_apps/atmosphere-smarttube.apk
#      where prebuilt_apps/Android.mk picks it up and system-signs it
#      with LOCAL_CERTIFICATE := platform at AOSP image-assembly time.
#
# The gradle-side signing (keystore.properties) is intentionally debug-
# signed; AOSP re-signs with the platform key during system.img build.
# This keeps local developer iteration simple — nobody needs access to
# the AOSP platform key to run a gradle assembly.
#
# Fails loudly if any step breaks so the main build.sh stops early
# rather than shipping a stale APK.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

cd "$SCRIPT_DIR"

echo "[ATMOSphere-SmartTube] build-atmosphere-smarttube.sh"
echo "  script dir: $SCRIPT_DIR"
echo "  parent:     $PARENT_ROOT"

# Provide a local keystore.properties if missing. Gradle looks for
# rootProject.file('keystore.properties') — without it, signingConfig
# release block is empty and assembleStstableRelease would fail the
# signing step. Use the Android debug keystore as a placeholder; AOSP
# re-signs with the platform key at image assembly time.
#
# Gradle property files do NOT expand `~` — it becomes a literal
# directory component relative to the module (smarttubetv/~). Use the
# absolute path via $HOME. Create the debug keystore if it's missing
# (fresh dev machine) using the standard password "android".
if [ ! -f keystore.properties ]; then
    _DEBUG_KS="$HOME/.android/debug.keystore"
    if [ ! -f "$_DEBUG_KS" ]; then
        echo "[ATMOSphere-SmartTube] creating $_DEBUG_KS (fresh machine; standard debug passwords)"
        mkdir -p "$HOME/.android"
        keytool -genkey -v \
            -keystore "$_DEBUG_KS" \
            -storepass android -keypass android \
            -alias androiddebugkey \
            -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA -keysize 2048 -validity 10000 2>&1 | tail -2
    fi
    echo "[ATMOSphere-SmartTube] generating keystore.properties (debug-signed placeholder; AOSP re-signs)"
    cat > keystore.properties <<EOF
# Auto-generated by build-atmosphere-smarttube.sh — DO NOT COMMIT.
# Gradle signing with the Android debug keystore is fine here because
# AOSP re-signs the APK with the platform key at system-image assembly
# time (see prebuilt_apps/Android.mk: LOCAL_CERTIFICATE := platform).
storeFile=$_DEBUG_KS
storePassword=android
keyAlias=androiddebugkey
keyPassword=android
EOF
fi

# Resolve JAVA_HOME carefully. SmartTube upstream pins gradle 7.5
# which was released before Java 21 support — running it under Java 21
# fails during Groovy semantic analysis with
# "Unsupported class file major version 65". Gradle 7.5 needs Java 8..17.
#
# Preference order (first that exists wins):
#   1. User-provided JAVA_HOME if it already points at a JDK ≤ 17.
#   2. AOSP prebuilt jdk17 (any known linux-x86 path variant).
#   3. System java-17-openjdk.
#   4. /usr/lib/jvm/jre-17-openjdk (some distros install JRE-only).
#   5. Fallback: /usr/bin/java via unset JAVA_HOME with a warning (build
#      may fail but at least we surface the issue instead of silently
#      using an incompatible JDK).
_pick_jdk17() {
    # If JAVA_HOME is already a 17 JDK, keep it.
    if [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/java" ]; then
        _v=$("$JAVA_HOME/bin/java" -version 2>&1 | head -1)
        case "$_v" in
            *'"17'*|*'"11'*|*'"1.8'*|*'"8'*)
                return 0 ;;
        esac
    fi
    for cand in \
        "$PARENT_ROOT/prebuilts/jdk/jdk17/linux-x86" \
        "$PARENT_ROOT/prebuilts/jdk/jdk17" \
        /usr/lib/jvm/java-17-openjdk \
        /usr/lib/jvm/java-17-openjdk-amd64 \
        /usr/lib/jvm/java-17-openjdk-*.x86_64 \
        /usr/lib/jvm/jre-17-openjdk \
        /usr/lib/jvm/jre-17-openjdk-amd64 \
        /usr/lib/jvm/jre-17-openjdk-*.x86_64; do
        # Resolve glob if any entry is literal (shell matches the first
        # real path) or skip if no match.
        for actual in $cand; do
            if [ -x "$actual/bin/java" ]; then
                export JAVA_HOME="$actual"
                return 0
            fi
        done
    done
    echo "[ATMOSphere-SmartTube] WARNING: no JDK 17 found — gradle 7.5 will fail on Java ≥ 18"
    unset JAVA_HOME
    return 1
}
_pick_jdk17 || true
if [ -n "${JAVA_HOME:-}" ]; then
    echo "[ATMOSphere-SmartTube] JAVA_HOME=$JAVA_HOME"
    "$JAVA_HOME/bin/java" -version 2>&1 | head -1
fi

# Guard against network-hostile CI: Gradle will try to download
# ~1.5 GB of artifacts on first run. Developers should run this once
# with network; CI caches ~/.gradle between runs.
# Ensure the gradle wrappers (main + nested submodules) are executable.
# Git submodule clones may land without the +x bit (depends on the
# developer's clone settings + whether umask stripped it).
for gw in ./gradlew SharedModules/gradlew MediaServiceCore/gradlew; do
    [ -f "$gw" ] && chmod +x "$gw" 2>/dev/null || true
done

echo "[ATMOSphere-SmartTube] running: ./gradlew :smarttubetv:assembleStstableRelease"
bash ./gradlew :smarttubetv:assembleStstableRelease --no-daemon --console=plain

# Find the built APK. Gradle produces ABI splits (arm64-v8a,
# armeabi-v7a, x86, universal). For a system-installed app on the
# RK3588 target, prefer the universal APK (contains all ABIs and
# survives any future multi-arch framework change). Fall back to
# arm64-v8a if universal isn't built, then any .apk as last resort.
APK_OUT_DIR=smarttubetv/build/outputs/apk/ststable/release
APK_PATH=""
for candidate in \
    "$APK_OUT_DIR"/*universal*.apk \
    "$APK_OUT_DIR"/*arm64-v8a*.apk \
    "$APK_OUT_DIR"/*.apk; do
    # Skip unexpanded globs.
    [ -f "$candidate" ] || continue
    # Skip x86 / armeabi-v7a — rk3588 is pure arm64.
    case "$(basename "$candidate")" in
        *x86*) continue ;;
        *armeabi-v7a*) continue ;;
    esac
    APK_PATH="$candidate"
    break
done
if [ -z "${APK_PATH:-}" ] || [ ! -f "$APK_PATH" ]; then
    echo "[ATMOSphere-SmartTube] ERROR: gradle reported success but no universal / arm64 APK under $APK_OUT_DIR"
    ls -la "$APK_OUT_DIR" 2>&1 | head -10
    exit 2
fi
echo "[ATMOSphere-SmartTube] built APK: $APK_PATH"

DEST="$PARENT_ROOT/device/rockchip/rk3588/prebuilt_apps/atmosphere-smarttube.apk"
cp -f "$APK_PATH" "$DEST"
echo "[ATMOSphere-SmartTube] copied to: $DEST"
ls -lh "$DEST"

echo "[ATMOSphere-SmartTube] done. scripts/build.sh will pick this APK"
echo "  up via device/rockchip/rk3588/prebuilt_apps/Android.mk and re-"
echo "  sign with the platform key at system-image assembly."
