#!/usr/bin/env bash
# build-atmosphere-smarttube.sh — build the ATMOSphere-SmartTube APK and
# copy it into the ATMOSphere prebuilt-apps tree for inclusion in the
# system image.
#
# Usage (from ATMOSphere parent repo root OR from this directory):
#     bash device/rockchip/atmosphere/smarttube-player/build-atmosphere-smarttube.sh
# or simply
#     cd device/rockchip/atmosphere/smarttube-player && bash build-atmosphere-smarttube.sh
#
# What it does:
#   1. Locates the ATMOSphere parent repo root (contains scripts/build.sh).
#   2. Runs ./gradlew :smarttubetv:assembleStstableRelease in this
#      submodule to produce the release APK (stable flavor →
#      applicationId org.smarttube.stable).
#   3. Copies the APK to
#      <atmosphere>/device/rockchip/rk3588/prebuilt_apps/atmosphere-smarttube.apk
#      where prebuilt_apps/Android.mk picks it up and system-signs it
#      with LOCAL_CERTIFICATE := platform at AOSP image-assembly time.
#
# The gradle-side signing (keystore.properties) is intentionally debug-
# signed; AOSP re-signs with the platform key during system.img build.
# This keeps local developer iteration simple — nobody needs access to
# the AOSP platform key to run a gradle assembly.
#
# Fails loudly if any step breaks so the main build.sh stops early
# rather than shipping a stale APK.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

cd "$SCRIPT_DIR"

echo "[ATMOSphere-SmartTube] build-atmosphere-smarttube.sh"
echo "  script dir: $SCRIPT_DIR"
echo "  parent:     $PARENT_ROOT"

# Provide a local keystore.properties if missing. Gradle looks for
# rootProject.file('keystore.properties') — without it, signingConfig
# release block is empty and assembleStstableRelease would fail the
# signing step. Use the Android debug keystore as a placeholder; AOSP
# re-signs with the platform key at image assembly time.
if [ ! -f keystore.properties ]; then
    echo "[ATMOSphere-SmartTube] generating keystore.properties (debug-signed placeholder; AOSP re-signs)"
    cat > keystore.properties <<'EOF'
# Auto-generated by build-atmosphere-smarttube.sh — DO NOT COMMIT.
# Gradle signing with the Android debug keystore is fine here because
# AOSP re-signs the APK with the platform key at system-image assembly
# time (see prebuilt_apps/Android.mk: LOCAL_CERTIFICATE := platform).
storeFile=~/.android/debug.keystore
storePassword=android
keyAlias=androiddebugkey
keyPassword=android
EOF
fi

# Point the Android SDK / Java toolchain used by the gradle wrapper at
# the prebuilts shipped with AOSP so the build works on a clean
# checkout that has the AOSP source tree but no separate Android SDK
# install. Developers with their own SDK can override by exporting
# ANDROID_SDK_ROOT / JAVA_HOME before invoking this script.
export JAVA_HOME="${JAVA_HOME:-$PARENT_ROOT/prebuilts/jdk/jdk21/linux-x86}"
if [ ! -d "$JAVA_HOME" ]; then
    echo "[ATMOSphere-SmartTube] WARNING: JAVA_HOME=$JAVA_HOME not found — falling back to system java"
    unset JAVA_HOME
fi

# Guard against network-hostile CI: Gradle will try to download
# ~1.5 GB of artifacts on first run. Developers should run this once
# with network; CI caches ~/.gradle between runs.
echo "[ATMOSphere-SmartTube] running: ./gradlew :smarttubetv:assembleStstableRelease"
./gradlew :smarttubetv:assembleStstableRelease --no-daemon --console=plain

# Find the built APK. Gradle names it with a variant suffix; the
# exact file name varies across Android Gradle Plugin versions so
# locate by pattern.
APK_PATH=$(find smarttubetv/build/outputs/apk/ststable/release -type f -name '*.apk' 2>/dev/null | head -1)
if [ -z "${APK_PATH:-}" ] || [ ! -f "$APK_PATH" ]; then
    echo "[ATMOSphere-SmartTube] ERROR: gradle reported success but no APK found under smarttubetv/build/outputs/apk/ststable/release/"
    exit 2
fi
echo "[ATMOSphere-SmartTube] built APK: $APK_PATH"

DEST="$PARENT_ROOT/device/rockchip/rk3588/prebuilt_apps/atmosphere-smarttube.apk"
cp -f "$APK_PATH" "$DEST"
echo "[ATMOSphere-SmartTube] copied to: $DEST"
ls -lh "$DEST"

echo "[ATMOSphere-SmartTube] done. scripts/build.sh will pick this APK"
echo "  up via device/rockchip/rk3588/prebuilt_apps/Android.mk and re-"
echo "  sign with the platform key at system-image assembly."
